create table if not exists public.repositories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  description text,
  allowed_types text[] not null
    check (cardinality(allowed_types) between 1 and 3)
    check (
      allowed_types <@ array[
        'Hyperlink',
        'JPG',
        'PNG',
        'PDF',
        'DOCX',
        'PPTX',
        'XLSX',
        'MP3',
        'MP4'
      ]::text[]
    ),
  created_at timestamptz not null default now()
);

alter table public.repositories enable row level security;

drop policy if exists "Users can view their own repositories" on public.repositories;
drop policy if exists "Users can insert their own repositories" on public.repositories;
drop policy if exists "Users can update their own repositories" on public.repositories;
drop policy if exists "Users can delete their own repositories" on public.repositories;

create policy "Users can view their own repositories"
on public.repositories
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own repositories"
on public.repositories
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own repositories"
on public.repositories
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own repositories"
on public.repositories
for delete
to authenticated
using (auth.uid() = user_id);
