create table if not exists public.items (
  id bigint generated by default as identity primary key,
  repository_id bigint not null references public.repositories (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  source_mode text not null check (source_mode in ('link', 'upload')),
  item_type text not null
    check (
      item_type = any (
        array[
          'Hyperlink',
          'JPG',
          'PNG',
          'PDF',
          'DOCX',
          'PPTX',
          'XLSX',
          'MP3',
          'MP4'
        ]::text[]
      )
    ),
  original_url text,
  preview_title text,
  preview_description text,
  preview_image_url text,
  preview_site_name text,
  created_at timestamptz not null default now(),
  check (
    (source_mode = 'link' and original_url is not null)
    or
    (source_mode = 'upload')
  )
);

create index if not exists items_repository_id_idx on public.items (repository_id);
create index if not exists items_user_id_idx on public.items (user_id);

alter table public.items enable row level security;

drop policy if exists "Users can view their own items" on public.items;
drop policy if exists "Users can insert their own items" on public.items;
drop policy if exists "Users can update their own items" on public.items;
drop policy if exists "Users can delete their own items" on public.items;

create policy "Users can view their own items"
on public.items
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own items"
on public.items
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own items"
on public.items
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own items"
on public.items
for delete
to authenticated
using (auth.uid() = user_id);
